<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Berhasil menyimpan profile</name>
   <tag></tag>
   <elementGuidId>e1d21d33-748e-447a-b417-08d59a5cc156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notistack-snackbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notistack-snackbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7dfc098-92c1-4a21-b92c-16558e256788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notistack-snackbar</value>
      <webElementGuid>63aa9f71-57b1-4e5c-b727-4070eff73bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SnackbarItem-message</value>
      <webElementGuid>1690c9d7-6e2d-49dc-b36d-d118963f75d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berhasil menyimpan profile!</value>
      <webElementGuid>2975a117-bdd0-4cf8-b6fc-ed969a6ee8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notistack-snackbar&quot;)</value>
      <webElementGuid>f7fa9f2a-aa2a-43d6-a2d7-c520ffd90c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notistack-snackbar']</value>
      <webElementGuid>fb8e30ea-550a-44bf-bcb6-ac0726411494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>1f117288-fe09-4603-8069-4ce8326b5460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>41a42564-c520-47fd-a644-d24445aa2364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'notistack-snackbar' and (text() = 'Berhasil menyimpan profile!' or . = 'Berhasil menyimpan profile!')]</value>
      <webElementGuid>fd591a94-d860-491a-963d-178b9c0d5c35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
