<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login berhasil</name>
   <tag></tag>
   <elementGuidId>4c0439d3-21bd-4012-a539-48d01573a162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notistack-snackbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notistack-snackbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1563d7b5-b7e2-4b64-be6f-c0ff8010f69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notistack-snackbar</value>
      <webElementGuid>1429d6bf-a1b2-4098-aff4-f55d5c05f055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SnackbarItem-message</value>
      <webElementGuid>784792ed-16fb-4888-b31f-f49ad59e7753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login berhasil!</value>
      <webElementGuid>b65e7d36-8b93-488a-a8fd-f2f09872e987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notistack-snackbar&quot;)</value>
      <webElementGuid>6418282f-0e14-4e47-8dfd-96e3bce0fe19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notistack-snackbar']</value>
      <webElementGuid>01083a9e-1c2f-4ccf-a79f-c611f8b84472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>fe036325-deab-4591-9ba1-4aee1a95b1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>c334b739-f852-4309-a177-9dd45ae602af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'notistack-snackbar' and (text() = 'Login berhasil!' or . = 'Login berhasil!')]</value>
      <webElementGuid>9d39cf97-eb23-40e5-b3ff-13f4d13e0edb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
